parser: babel-eslint
extends: narazaka
env:
  es6: true
  node: true
  mocha: true
rules:
  consistent-return: 0
  no-magic-numbers: 0
  callback-return: 0
  init-declarations: 0
  no-loop-func: 0
  func-names: 0
  class-methods-use-this: 0
