version: "{build}"
branches:
  except:
    - gh-pages
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm install -g yarn
  - yarn --version
  - yarn install
test_script:
  - npm test
build: off
deploy: off
environment:
  matrix:
    - nodejs_version: 6
cache:
  - node_modules
